services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://job-tracker-app:8080
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
